apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-demo
spec:
  storageClassname: visitor-strgclass
  accessModes:
    - ReadWriteOnce
  capacity:
    requests:
      resources:
        stroage: 20Gi
