apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: visitor-mysql
provisioner: kubernetes.io/aws-ebs
parameters:
    type: gp2
    encrypted: 'true'
reclaimPolicy: Delete
mountOptions:
- debug
 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: visitor-mysql
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi